version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints: b8:20:1c:84:9e:98:73:4b:ef:66:9d:30:c9:01:55:e0

      # Run shell script on remote server
      - run:
          name: Run sudo
          command: 
            cd /home/opc
            
workflows:
  version: 2
  build:
    jobs:
      - build
